<%@ Page Title="" Language="C#" MasterPageFile="~/Sites.Master" AutoEventWireup="true" CodeBehind="DisplayDetails.aspx.cs" Inherits="WebApplication2.DisplayDetails" %>
<asp:Content ID="Master" ContentPlaceHolderID="Master" runat="server">
</asp:Content>
<asp:Content ID="DisplayDetail" ContentPlaceHolderID="Form" runat="server">
    <asp:GridView ID="userDetail" runat="server" AutoGenerateColumns="False" DataKeyNames="firstName" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
        <Columns>
            <asp:TemplateField HeaderText="FirstName" runat="server">
                <ItemTemplate>
                    <asp:Label ID="FirstName" runat="server" Text='<%# Bind("firstName") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="TxtId" runat="server" Text='<%# Bind("firstName") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="LastName" runat="server">
                <ItemTemplate>
                    <asp:Label ID="LastName" runat="server" Text='<%# Bind("lastName") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="TxtId" runat="server" Text='<%# Bind("lastName") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="MobilePhone" runat="server">
                <ItemTemplate>
                    <asp:Label ID="MobileNumber" runat="server" Text='<%# Bind("mobileNumber") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="TxtId" runat="server" Text='<%# Bind("mobileNumber") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="password" runat="server">
                <ItemTemplate>
                    <asp:Label ID="password" runat="server" Text='<%# Bind("password") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="TxtId" runat="server" Text='<%# Bind("password") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="gmail" runat="server">
                <ItemTemplate>
                    <asp:Label ID="gmail" runat="server" Text='<%# Bind("gmail") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="TxtId" runat="server" Text='<%# Bind("gmail") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="userType" runat="server">
                <ItemTemplate>
                    <asp:Label ID="userType" runat="server" Text='<%# Bind("userType") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="TxtId" runat="server" Text='<%# Bind("userType") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
